// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppResume struct {
	ID             pgtype.UUID
	Name           string
	OwnerUserID    pgtype.UUID
	Industry       string
	YoeBucket      string
	CurrentEloInt  int32
	BattlesCount   int32
	LastMatchedAt  pgtype.Timestamptz
	InFlight       bool
	CreatedAt      pgtype.Timestamptz
	PdfStorageKey  pgtype.Text
	PdfSizeBytes   pgtype.Int8
	PdfMime        string
	ImageKeyPrefix pgtype.Text
	PageCount      int16
	ImageReady     bool
	Slot           int16
}

type AuthUser struct {
	ID pgtype.UUID
}
