// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppFeedback struct {
	ID             pgtype.UUID
	MatchID        pgtype.UUID
	TargetResumeID pgtype.UUID
	AuthorUserID   pgtype.UUID
	Visibility     string
	Text           string
	Tags           []string
	CreatedAt      pgtype.Timestamptz
}

type AppMatch struct {
	ID              pgtype.UUID
	ResumeAID       pgtype.UUID
	ResumeBID       pgtype.UUID
	Industry        string
	YoeBucket       string
	CreatedAt       pgtype.Timestamptz
	ResolvedAt      pgtype.Timestamptz
	WinnerResumeID  pgtype.UUID
	LoserResumeID   pgtype.UUID
	DecidedByUserID pgtype.UUID
	KFactorUsed     pgtype.Int4
	DeltaA          pgtype.Int4
	DeltaB          pgtype.Int4
	Skipped         bool
	State           string
}

type AppResume struct {
	ID             pgtype.UUID
	Name           string
	OwnerUserID    pgtype.UUID
	Industry       string
	YoeBucket      string
	CurrentEloInt  int32
	BattlesCount   int32
	LastMatchedAt  pgtype.Timestamptz
	InFlight       bool
	CreatedAt      pgtype.Timestamptz
	PdfStorageKey  pgtype.Text
	PdfSizeBytes   pgtype.Int8
	PdfMime        string
	ImageKeyPrefix pgtype.Text
	PageCount      int16
	ImageReady     bool
	Slot           int16
}

type AuthUser struct {
	ID pgtype.UUID
}
